source "http://rubygems.org"
gem "sqlite3", :require => "sqlite3"
gem "itextomml"
gem "rack"
gem "thin"
gem "rubyzip"
gem "RedCloth"
gem "erubis"
gem "nokogiri", "1.5.11"
gem "rake"
gem "rdoc"
gem "json", "2.0.2"
gem "abstract"
gem "rails_xss"
gem "file_signature"
gem "syntax"
gem "maruku"
gem 'iconv'
gem 'test-unit'
gem "zip"

