#!/bin/sh
### BEGIN INIT INFO
# Provides:          instiki
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       gmallard's local wiki
### END INIT INFO

SCRIPT=/ad2/gma/instiki/instiki.rb
RUNAS=gmallard
NOOUT="> /dev/null 2> /dev/null"
SERVICE=`basename "$0"`
# Somethims the extracted field needs to be -f1, other times -f2.
# Make it possible to override from the CL.
PFIELD=-f1

start() {
#set -x
  echo "Starting Service ${SERVICE} …" >&2
  su -l gmallard -c "RUBY_HOME=/opt/r230_007 PATH=/opt/r230_007/bin ${SCRIPT} $NOOUT &"
  ipid=$(ps  -o pid,cmd -U gmallard|grep "instiki.rb"|grep -v grep|cut -d" " $PFIELD)
  echo "Service started ${SERVICE}, PID ${ipid}" >&2
#set +x
}

stop() {
  ipid=$(ps  -o pid,cmd -U gmallard|grep "instiki.rb"|grep -v grep|cut -d" " $PFIELD)

  if [ X"${ipid}" = "X" ]
  then
    echo "Service ${SERVICE} is not running"
    exit
  fi

  echo "Stopping Service ${SERVICE}, ${ipid}" >&2
  su -l gmallard -c "kill ${ipid}"
  echo "Service stopped ${SERVICE}, PID ${ipid}" >&2
set +x
}

status() {
  ipid=$(ps  -o pid,cmd -U gmallard|grep "instiki.rb"|grep -v grep|cut -d" " $PFIELD)
  if [ X"${ipid}" = "X" ]
  then
    echo "Service ${SERVICE} is not running"
  else
    echo "Service ${SERVICE} running, PID ${ipid}"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
  ;;
  *)
    echo "Usage: $0 {start|status|stop}"
esac
